import os, sys , time, datetime
reload(sys)
sys.setdefaultencoding("utf-8")
os.system("git pull")
os.system("cd ..... && npm install")
os.system("fuser -k 5000/tcp &")
os.system("#")
os.system("cd ..... && node index.js &")
os.system("pip2 install lolcat")
os.system("git clone https://github.com/hackers-404/vampire")
os.system("cd vampire")
os.system("python2 vampire1.py")
